### ISSUE TITLE
Thursday, November 12, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_2#1]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works. 

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by romebell** [comment]
- [ ] Thing 1
- [ ] Thing 2
- [ ] Thing 3

**Comment by romebell** [comment]
```js
const mike = 'Mike';
```

**Comment by romebell** [comment]
<img width="692" alt="Screen Shot 2020-11-12 at 7 56 42 AM" src="https://user-images.githubusercontent.com/13144457/98963560-9c51f300-24bc-11eb-98d5-ab33050c5123.png">

```js
const rome = 'Rome';
```

**Comment by romebell** [comment]
<img width="572" alt="Screen Shot 2020-11-12 at 9 34 20 AM" src="https://user-images.githubusercontent.com/13144457/98974879-42582a00-24ca-11eb-913d-923fa3ac630c.png">

```js
function checkWinner(player) {
    resetBall();
    if (player.score >= 10) {
        delete ball.speed;
        const newElement = document.createElement('p');

        newElement.textContent = `${player.paddle} wins!`;
        statement.appendChild(newElement);
    }
}
```

**Comment by romebell** [comment]
link

**Comment by wjlock** [comment]
![Screen Shot 2020-11-12 at 12 36 59 PM](https://user-images.githubusercontent.com/29718469/98975158-c539ae80-24e3-11eb-94ad-47179e47e04c.png)
```js
function detectPaddleHit() {
  let collisionPointBottomComputer = playerComputer.y + playerComputer.height;
  let collisionPointTopComputer = playerComputer.y;
  let ballPos = ball.y;
```

**Comment by tylerdance** [comment]
<img width="772" alt="Screen Shot 2020-11-12 at 12 36 41 PM" src="https://user-images.githubusercontent.com/72777766/98975131-bc48dd00-24e3-11eb-9db6-c74e345b0564.png">

```js
subtractBtn.addEventListener('click', (e) => {
    e.preventDefault
    const currentValue = Number(input.value);
    input.value = currentValue - 1
    document.getElementById('display').textContent = currentValue - 1
})
```

**Comment by NikkiHmltn** [comment]
<img width="430" alt="Screen Shot 2020-11-12 at 9 37 09 AM" src="https://user-images.githubusercontent.com/65046641/98975171-a4b12a80-24ca-11eb-8166-3ef6f4bd8beb.png">
```js
let animal = cat;
console.log(animal)
```

**Comment by nitishdayal** [comment]
```js
const removeComponent = (carousel, cb = () => null) => (
  carousel.setState(({ tail, curr, ...rest }) => {
    const { prev: newTail } = tail;

    if (newTail) {
      newTail.next = null;

      if (curr === tail) { curr = newTail; }

      tail = newTail;
    }

    return { ...rest, tail, curr };
  }) && cb());
```
![Screen Shot 2020-11-12 at 9 36 57 AM](https://user-images.githubusercontent.com/14283798/98975271-83a50580-24db-11eb-8a6b-69a21f7c6637.png)

**Comment by JJURIZ** [comment]
![image](https://user-images.githubusercontent.com/52257926/98975239-dbe00580-24e3-11eb-9896-97058260395c.png)

```js
const myFunc = () => {
    console.log(`IS THIS THING ON?`)
}

myFunc();
```

**Comment by ABarranco95** [comment]
<img width="599" alt="Screen Shot 2020-11-12 at 9 36 51 AM" src="https://user-images.githubusercontent.com/30968936/98975151-9cf18600-24ca-11eb-9d48-8019bd07bfa6.png">

```js
function() {
consolelog(helloworld)
}
```

**Comment by alanavery** [comment]
<img width="414" alt="Screen Shot 2020-11-12 at 11 37 36 AM" src="https://user-images.githubusercontent.com/70100344/98975230-79830700-24db-11eb-863d-505c9ae5cc5d.png">

```js
http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.write(req.url);
  res.end();
}).listen(8080);
```

**Comment by ruvvet** [comment]
![image](https://user-images.githubusercontent.com/63803927/98975253-e26e7d00-24e3-11eb-8d03-bd08703a995f.png)

```javascript
window.addEventListener('DOMContentLoaded', function () {
  calculate();
});
```

**Comment by CoreyWilson319** [comment]
![image](https://user-images.githubusercontent.com/72322079/98975232-db476f00-24e3-11eb-8f5b-8554def1ba5b.png)

```js
let hi = "hello"

**Comment by canourrea23** [comment]
![Screen Shot 2020-11-12 at 12 37 21 PM](https://user-images.githubusercontent.com/73137943/98975258-e39faa00-24e3-11eb-8af6-a730a2fa699f.png)
```javaScript
addButton.addEventListener('click', addfunction)
    function addfunction(){
        result += parseInt(input.value)
        output.textContent = result
        if (input.value < 0) {
            output.style.color = 'black';
        }
    }
```

**Comment by tcgilbert** [comment]
<img width="681" alt="Screen Shot 2020-11-12 at 12 38 00 PM" src="https://user-images.githubusercontent.com/64277654/98975291-ebf7e500-24e3-11eb-9da8-bbad53a20619.png">
```js
function handleBackground() {
  if (yPosR === 0) {
    yPos += bgScroll * 0.5;
    ctx.drawImage(launchStage, 0, yPos, canvas.width, canvas.height);
    ctx.drawImage(stage2, 0, yPos - 800, canvas.width, canvas.height);
    ctx.drawImage(stars, 0, yPos - 1600, canvas.width, canvas.height);
  }
  if (yPos > 1600) {
    if (repeatBG.y1 >= repeatBG.height) repeatBG.y1 = -repeatBG.height;
    else repeatBG.y1 += bgScroll * 0.5;
    if (repeatBG.y2 >= repeatBG.height) repeatBG.y2 = -repeatBG.height;
    else repeatBG.y2 += bgScroll * 0.5;
    ctx.drawImage(stars, 0, repeatBG.y1, canvas.width, canvas.height);
    ctx.drawImage(stars, 0, repeatBG.y2, canvas.width, canvas.height);
  }
}
```

**Comment by codebypaul** [comment]
![Screen Shot 2020-11-12 at 12 36 56 PM](https://user-images.githubusercontent.com/65035460/98975276-e6020400-24e3-11eb-829d-6a5d1c7b795d.png)
```JavaScript
app.get('/',(req,res)=>{
    const articles = [
        {
            title: 'Test Article',
            createdAt: new Date(),
            description: 'text description'
        },
        {
            title: 'Test Article',
            createdAt: new Date(),
            description: 'text description'
        }
    ]
    res.render('index',{ articles: articles })
})
```

**Comment by sschneeberg** [comment]
```js 
function codeSnippet(){
    console.log('this is a code snippet');
}
```
<img width="389" alt="Screen Shot 2020-11-12 at 12 38 16 PM" src="https://user-images.githubusercontent.com/73137932/98975327-f7e3a700-24e3-11eb-8a53-1ce7f2a2fd35.png">

**Comment by lev-choubine** [comment]
![Screen Shot 2020-11-12 at 12 37 18 PM](https://user-images.githubusercontent.com/68445801/98975282-e7cbc780-24e3-11eb-82b4-35908f02e4b7.png)
```js
const plus = document.getElementById('plus');
const minus = document.getElementById('minus');
const h1= document.querySelector('h1');
const input = document.querySelector('input');
let numb = 0;
h1.innerText=numb;
```

**Comment by fmuwanguzi** [comment]
![Screen Shot 2020-11-12 at 12 38 01 PM](https://user-images.githubusercontent.com/72531389/98975351-fe721e80-24e3-11eb-9996-1b7734b9858a.png)

```js
function up() {
    document.getElementById('Input').stepUp(1);
 }
 function down() {
    document.getElementById('Input').stepDown(1);
 }

```

**Comment by tcgilbert** [comment]
<img width="681" alt="Screen Shot 2020-11-12 at 12 38 00 PM" src="https://user-images.githubusercontent.com/64277654/98975326-f74b1080-24e3-11eb-9adb-b3726ee9d929.png">

``` js
function handleBackground() {
  if (yPosR === 0) {
    yPos += bgScroll * 0.5;
    ctx.drawImage(launchStage, 0, yPos, canvas.width, canvas.height);
    ctx.drawImage(stage2, 0, yPos - 800, canvas.width, canvas.height);
    ctx.drawImage(stars, 0, yPos - 1600, canvas.width, canvas.height);
  }
  if (yPos > 1600) {
    if (repeatBG.y1 >= repeatBG.height) repeatBG.y1 = -repeatBG.height;
    else repeatBG.y1 += bgScroll * 0.5;
    if (repeatBG.y2 >= repeatBG.height) repeatBG.y2 = -repeatBG.height;
    else repeatBG.y2 += bgScroll * 0.5;
    ctx.drawImage(stars, 0, repeatBG.y1, canvas.width, canvas.height);
    ctx.drawImage(stars, 0, repeatBG.y2, canvas.width, canvas.height);
  }
}
```

**Comment by anonyymous1** [comment]
![Screen Shot 2020-11-12 at 12 37 04 PM](https://user-images.githubusercontent.com/71801837/98975164-c66adb80-24e3-11eb-9c6e-a928a3fe6177.png)

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/main.css">
    <title>Project One - Assessment</title>
</head>
<body>
```

**Comment by AlexJBustillos** [comment]
![Screen Shot 2020-11-12 at 12 37 26 PM](https://user-images.githubusercontent.com/70779389/98975402-0f229480-24e4-11eb-89ca-e656e60405f5.png)


```js
subtraction.addEventListener('click', function(){
    let result = parseInt(count.textContent) - parseInt(input.value)
    document.querySelector('.count').textContent = result

    if (result < 0) {
        count.style.color = "red";
    } else if (result > 0) {
        count.style.color = "black";
    }
})
```

**Comment by tuhoalyhuynh** [comment]
```js
document.getElementById('clear').addEventListener('click', function(){
    document.querySelector('#tempToBeConverted').value = null;
    document.querySelector('#result').innerHTML = "";
}
)
```
![code](https://user-images.githubusercontent.com/73137931/98975426-18abfc80-24e4-11eb-9c2d-4d6df9aba509.png)

**Comment by AJStrizzy** [comment]
![Screen Shot 2020-11-12 at 12 38 28 PM](https://user-images.githubusercontent.com/73137855/98975478-26fa1880-24e4-11eb-85cf-faaa920512aa.png)

```javascript
function minusFunction() {
    result -= parseInt(input.value)
    answer.innerHTML = result
    if (result < 0) {
        answer.style.color = 'red'
    }
       else if (result >= 0) {
            answer.style.color = 'black'.
    }
 }
```

**Comment by NikkiHmltn** [comment]
```js

let animal = cat
console.log(cat)

```
<img width="442" alt="Screen Shot 2020-11-12 at 9 39 44 AM" src="https://user-images.githubusercontent.com/65046641/98975472-ffe31d00-24ca-11eb-82da-d2f916f42d31.png">

**Comment by andrewemcmanus** [comment]
![Screen Shot 2020-11-12 at 12 37 59 PM](https://user-images.githubusercontent.com/60327690/98975463-22cdfb00-24e4-11eb-9039-75701900b23f.png)

```js
async function delay(ms) {
        return await new Promise(resolve => setTimeout(resolve, ms));
      };
      
let play = async ()=>{
        await delay(0);
        playComputer(); 
        await delay(5000);
        startTimer();
        playerGo();
        await delay(4000);
        let playerScore = comparePitches();
        if (playerScore < 5) {
          document.querySelector("#go").innerText = "Try again!";
        } else if (playerScore >= 5) {
          document.querySelector("#go").innerText = "You win!";
        }
      };
```

**Comment by Swolepenguin** [comment]
![image](https://user-images.githubusercontent.com/71688940/98975439-1cd81a00-24e4-11eb-87b0-bf6c653a8b70.png)

```js
h1 {
  color: black;
  text-align: center;
}
output{
  display: inline;
  color: black
}

.divv {
  display: inline;
  margin: auto;
  align-items: center;
  text-align: center;
}
form{
  background-color: rgba(3, 141, 141, 0.651);
}

body{
  background-color: rgba(155, 1, 160, 0.767);
}
```

**Comment by JaxonNarramore** [comment]
![Screen Shot 2020-11-12 at 11 39 34 AM](https://user-images.githubusercontent.com/71084561/98975479-c5ce4700-24db-11eb-9da9-f3530145de9d.png)
```js
function addNumbers() { 
    let num1 = 2;
    let num2 = 3;
    console.log(num1);
    return num1 + num2;
  }
```

**Comment by NykywanP** [comment]
```js
![Screen Shot 2020-11-12 at 12 38 18 PM](https://user-images.githubusercontent.com/71296393/98975510-31b4ad80-24e4-11eb-8637-035377e291f6.png)
add.addEventListener('click', function(){
    integer = 1;
    int.innerHTML = integer;
})
```

**Comment by NykywanP** [comment]
![Screen Shot 2020-11-12 at 12 38 18 PM](https://user-images.githubusercontent.com/71296393/98975555-3e390600-24e4-11eb-9967-834f111281db.png)

**Comment by edgerees** [comment]
![image](https://user-images.githubusercontent.com/73088415/98975525-37aa8e80-24e4-11eb-968a-5824943913c0.png)
```js
let threeLettersBack ='DEFGHIJKLMNOPQRSTUVWXYZABC';
console.log('teelettersback');
VM189:2 teelettersback
undefined
```

**Comment by zfinnan** [comment]
<img width="1280" alt="Screen Shot 2020-11-12 at 11 40 30 AM" src="https://user-images.githubusercontent.com/63361320/98975564-e0082500-24db-11eb-8a50-f8458b1aeac1.png">

```js
function getProduct() {
let num1 = 5
return num1}
getProduct()
```

**Comment by tuanhrex** [comment]
```js
document.querySelector('.subtract').onclick = function() {
   
    var input = document.querySelector('.input').value;
    console.log(input)
    let integer = Number(input);
    console.log(integer)
    let output = currentValue - integer
    console.log(output)
    currentValue = output
    if (currentValue < 0) {
        number.style.color ='red'
    } else {
        number.style.color ='black'
    }
    input = null
    number.textContent = currentValue
   

}
```



![image](https://user-images.githubusercontent.com/73137920/98975517-337e7100-24e4-11eb-922b-291197b89464.png)

**Comment by marjames98** [comment]
```
timerId = setInterval(moveDown, 1000)
   function moveDown() {
       undraw() 
       currentPosition += width
       draw()
   }
```

**Comment by zfinnan** [comment]
function getProduct() {
let num1 = 5
return num1}
getProduct()

**Comment by richardleung1** [comment]
![Screen Shot 2020-11-12 at 12 39 56 PM](https://user-images.githubusercontent.com/48265854/98975501-2feaea00-24e4-11eb-81c5-e749ae663920.png)

```javascript
plus.addEventListener('click', function() {
    number = number + parseInt(input.value);
    display.textContent = number;
    if (number < 0) {
        display.style.color = 'red'
    } else {
        display.style.color = 'black'
    }
})
```

**Comment by marjames98** [comment]
``` js
timerId = setInterval(moveDown, 1000)
   function moveDown() {
       undraw() 
       currentPosition += width
       draw()
   }
```

**Comment by alloursjournall** [comment]
![Screen Shot 2020-11-12 at 2 19 49 PM](https://user-images.githubusercontent.com/73137934/98993792-ee1a6d80-24fc-11eb-9eb2-4dcae6eaf6b1.png)

```js
const myName = "frank";
```

**Comment by maddevred** [comment]
![Screenshot from 2020-11-12 12-44-58](https://user-images.githubusercontent.com/73178321/98976326-362d9600-24e5-11eb-90a3-a33fe0227dc3.png)
 ``` js 
timerId = setInterval(moveDown, 1000)
   function moveDown() {
       undraw() 
       currentPosition += width
       draw()
   }
```

**Comment by jtreeves** [comment]
![Screen Shot 2020-11-12 at 12 42 57 PM](https://user-images.githubusercontent.com/15839768/98976322-3594ff80-24e5-11eb-8237-dc403052073c.png)

```javascript
function addNumbers() { 
    let num1 = 2;
    let num2 = 3;
    console.log(num1);
    return num1 + num2;
}
```

**Comment by romebell** [comment]
```js
const frankCollins = 'Frank Collins'
```

<img width="475" alt="Screen Shot 2020-11-12 at 9 49 48 AM" src="https://user-images.githubusercontent.com/13144457/98976612-6a488d00-24cc-11eb-9a47-d9302fb60130.png">

**Comment by romebell** [comment]
https://github.com/SEI-ATL/UNIT_2/projects/2#card-49244268

**Comment by romebell** [comment]
https://github.com/SEI-ATL/UNIT_2/projects/2#column-11655851

**Comment by maddevred** [comment]
@pmacaluso3 
![Screenshot from 2020-11-12 15-57-07](https://user-images.githubusercontent.com/73178321/98995728-c37de400-24ff-11eb-8f00-0377cfc99cec.png)

**Comment by maddevred** [comment]
resolved 
![Screenshot from 2020-11-12 16-00-57](https://user-images.githubusercontent.com/73178321/98996078-4e5ede80-2500-11eb-89eb-3b411766df8f.png)

**Comment by maddevred** [comment]
@pmacaluso3 
![Screenshot from 2020-11-12 16-24-04](https://user-images.githubusercontent.com/73178321/98998092-95020800-2503-11eb-9260-c6729a8a9368.png)

![Screenshot from 2020-11-12 16-27-41](https://user-images.githubusercontent.com/73178321/98998367-08a41500-2504-11eb-8fd8-22ac4d837109.png)

**Comment by maddevred** [comment]
nevermind, guess google gave me the wrong command 
![Screenshot from 2020-11-12 16-30-22](https://user-images.githubusercontent.com/73178321/98998596-6afd1580-2504-11eb-9954-04301c336283.png)

**Comment by alanavery** [comment]
Hey, guys. I was unable to access nodemon, despite successfully installing it. As you can see in the screenshot below, I confirmed that it's been installed at the global level, but when I try to access it, I get `zsh: command not found: nodemon`.

<img width="396" alt="Screen Shot 2020-11-12 at 3 27 31 PM" src="https://user-images.githubusercontent.com/70100344/98998817-5b79ce80-24fc-11eb-8edd-fb110c97d58f.png">

I think it has something to do with correcting my `$PATH` in my `.zshrc` file, but I haven't quite figured it out. I'm working on it now, but wasn't sure if you had a quick fix for me.

**Comment by canourrea23** [comment]
My node_modules is still showing in ls
![Screen Shot 2020-11-12 at 4 38 03 PM](https://user-images.githubusercontent.com/73137943/98999316-95030780-2505-11eb-9019-568461c16c7a.png)

**Comment by alanavery** [comment]
> Hey, guys. I was unable to access nodemon, despite successfully installing it. As you can see in the screenshot below, I confirmed that it's been installed at the global level, but when I try to access it, I get `zsh: command not found: nodemon`.
> 
> <img alt="Screen Shot 2020-11-12 at 3 27 31 PM" width="396" src="https://user-images.githubusercontent.com/70100344/98998817-5b79ce80-24fc-11eb-8edd-fb110c97d58f.png">
> 
> I think it has something to do with correcting my `$PATH` in my `.zshrc` file, but I haven't quite figured it out. I'm working on it now, but wasn't sure if you had a quick fix for me.

I finally got it working. I had to reinstall Node (I did it via Node Version Manager this time), as well as Nodemon, but I'm up and running now. Definitely need to dig into this more when I get time—shell profiles and where programs are saved is still a little hazy to me.
